[package]
name = "orb"
version = "0.0.0"
edition = "2024"
authors = ["Nick Krantz"]
description = "CLI tool for doing repetitive tasks"

[dependencies]
clap = { version = "4.5.50", features = ["derive"] }
dirs = "6.0.0"
